<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDLbX7lm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDLbX7lm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDLbX7lm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDLbX7lm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDLbX7lm\App_KernelDevDebugContainer([
    'container.build_hash' => 'DLbX7lm',
    'container.build_id' => '009d187e',
    'container.build_time' => 1694540394,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDLbX7lm');
